version: '3.6'
services:
  postgres:
    image: postgres:11
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restdb
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always